services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8081:80'
    depends_on:
      - postgres
    networks:
      - postgres

  redis:
    container_name: redis-cache
    image: redis:7.4.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    depends_on:
      - redis

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis:
